name: Client CI

on:
  push:
    branches: [master]
    paths:
      - "client/**"
  pull_request:
    branches: [master]
    paths:
      - "client/**"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} lint, test and coverage
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Builds frontend
    - run : docker-compose up -d client
    
    - name: Run tests
    - run: docker-compose run client quasar test --unit jest  