version: "3.9"
   
services:
  db:
    image: postgres
    build: ./api/db
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=myproject
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  api:
    build: ./api/
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    depends_on:
      - db