name: API CI

on: 
  push:
    branches: [master]
    paths:
      - "api/**"
  pull_request:
    branches: [master]
    paths:
      - "api/**"

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgress:
        image: postgres
        env:
          POSTGRES_DB=myproject
          POSTGRES_USER=myuser
          POSTGRES_PASSWORD=password
        ports:
          - 5432:5432
    
    steps:
    - uses: docker-compose up -d api
    - name: Builds API
        
    - name: Run Tests
    - run: python manage.py test
      working-directory: api
      env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: github-actions
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432