name: Client CI

on:
  push:
    branches: [master]
    paths:
      - "client/**"
  pull_request:
    branches: [master]
    paths:
      - "client/**"

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }} lint, test and coverage
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - working-directory: client
        run: |
          yarn install
          yarn lint
      - name: Coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: a62422ecf29b56b7ad5e56d69443c5b268664ae894f867e7c81d0acaf03df621
        with:
          coverageCommand: yarn test:unit:coverage
          debug: true